# ================================
# Training
# ================================
n_batch_size: 64
batch_size: 64
device: cuda
lr: 0.001
num_epochs: 50
n_workers: 0
model: tf_transformer
optimizer: adamw
weight_decay: 0.0001
loss: huber
huber_delta: 1.0
point_forecast: true
use_quantile_loss_for_tft: false
amp: false
grad_accum_steps: 1

# ================================
# Dataset
# ================================
ds_name: air_quality

# Đặt số lượng lớn để lấy 100% data
train_samples: -1
test_samples: -1
val_samples: -1

input_size: 18
output_size: 1

total_time_steps: 25
num_encoder_steps: 24

# feature positions
static_input_loc: 
- 17
input_obs_loc:
- 0

known_categorical_inputs: []
known_regular_inputs:
# ĐÃ XÓA - 0 Ở ĐÂY ĐỂ TRÁNH RÒ RỈ DỮ LIỆU TƯƠNG LAI
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16

category_counts: 
- 3 # Cập nhật thành 3 vì bạn đang dự báo cho 3 địa điểm (An Giang, Bắc Giang, Bắc Kạn)

# ================================
# Temporal Fusion Transformer
# ================================
quantiles:
- 0.5

batch_first: true
early_stopping_patience: 5
hidden_layer_size: 64
stack_size: 1
dropout_rate: 0.1
max_gradient_norm: 1.0
num_heads: 4
multiprocessing_workers: 5

# ================================
# Transformer
# ================================
d_model: 64
q: 16
v: 16
h: 4
N: 2
attention_size: 0
dropout: 0.1
pe: original
chunk_mode: None

d_input: 18
d_output: 1
use_location_token: true
location_input_idx: 17
location_vocab_size: 256